### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [Jeremy-Ramirez/ISII-WORKSHOPS-AGENCIA_LABORAL#1]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by Jeremy-Ramirez** [comment]
The issue has been reproduced.

**Comment by Jeremy-Ramirez** [comment]
The issue has been categorized.

**Comment by Jeremy-Ramirez** [comment]
We will process the request, @diacrami will be assigned analyst and develop the solution, @NicoleAsqui will perfom the tests.

**Comment by diacrami** [comment]
@jose598 Here is the impact analysis, please tell us if you agree to the estimation and resources required to perform the change
[Impact analysis.docx](https://github.com/Jeremy-Ramirez/ISII-WORKSHOPS-AGENCIA_LABORAL/files/7908014/Impact.analysis.docx)
.

**Comment by jose598** [comment]
Thank @diacrami.
Please start working on the issue.

**Comment by diacrami** [comment]
@jose598  The solution has been built.
https://github.com/Jeremy-Ramirez/ISII-WORKSHOPS-AGENCIA_LABORAL/blob/55ca0068fe52f53ab8bb83386b18223a0c1f339f/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L74-L103

**Comment by jose598** [comment]
I have observation, the discount according to the first case/rule is about $100, because the discount is $50 for each one.

Please change this and on your analysis report. 
@diacrami

**Comment by diacrami** [comment]
@jose598 The correction has been made.
https://github.com/Jeremy-Ramirez/ISII-WORKSHOPS-AGENCIA_LABORAL/blob/86f3e72c24a9091df0e611e7656e27e108445002/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L74-L103

**Comment by jose598** [comment]
Thank you. 
Now It looks good. @diacrami

**Comment by NicoleAsqui** [comment]
[TESTING.docx](https://github.com/Jeremy-Ramirez/ISII-WORKSHOPS-AGENCIA_LABORAL/files/7917510/TESTING.docx)

@jose598  The tests have been carried out, I attach the respective document

**Comment by jose598** [comment]
Thank you @NicoleAsqui .
Please, continue with the release

**Comment by NicoleAsqui** [comment]
[Acceptance Test Plan.docx](https://github.com/Jeremy-Ramirez/ISII-WORKSHOPS-AGENCIA_LABORAL/files/7917545/Acceptance.Test.Plan.docx)
Thank you, I attach the test document so you can review it please @jose598

**Comment by jose598** [comment]
@NicoleAsqui I already checked it out. So continue with the next step

**Comment by Jeremy-Ramirez** [comment]
@jose598 The solution has been completed and @diacrami wil release the new software version for you.

**Comment by jose598** [comment]
@Jeremy-Ramirez Thank you.

**Comment by diacrami** [comment]
@jose598 Here are the instructions to download and use the software

[Instructions to use the Software.docx](https://github.com/Jeremy-Ramirez/ISII-WORKSHOPS-AGENCIA_LABORAL/files/7917623/Instructions.to.use.the.Software.docx)
.

**Comment by jose598** [comment]
Thank you @diacrami.

I already approved this change with our system. 
Everything sounds good.

**Comment by Jeremy-Ramirez** [comment]
@jose598 Are you satisfied with the solution?

**Comment by jose598** [comment]
@Jeremy-Ramirez Yes I am.
You can close the issue

**Comment by Jeremy-Ramirez** [comment]
@jose598  Thank you i will proceed to close the issue
